### ISSUE TITLE
fixed by https://github.com/cocos-creator-packages/jsb-adapter/pull/319 , thanks anyway

### ISSUE THREAD

**Issue by murataka** [cocos-creator-packages/jsb-adapter#326]
fixed by https://github.com/cocos-creator-packages/jsb-adapter/pull/319 , thanks anyway

_Originally posted by @holycanvas in https://github.com/cocos-creator-packages/jsb-adapter/pull/315#issuecomment-664755026_

The output is as follows on xCode:

initWithImageFile: /var/mobile/Containers/Data/Application/E5262E71-C924-4544-9D4B-499065A6B26C/Documents//gamecaches/15971584922530.jpg failed!

Cocos Creator version 2.4.2 

The problem seems to persist... Check out // part after "Documents"

**Comment by holycanvas** [comment]
I'm not sure why is it. I think I have already used RegExp to trim these slashes by #319 . You have any information?

**Comment by murataka** [comment]
i have just tested on device , using remote images (published game). i will try to debug and see what is happening, and will share if i can. 

This just happens on ios platform , not android.

**Comment by murataka** [comment]
i checked and regex solution works fine. unfortunately, creater version 2.4.2 does not include this fix.

**Comment by holycanvas** [comment]
> i checked and regex solution works fine. unfortunately, creater version 2.4.2 does not include this fix.

Sorry，It has been merged into v2.4.3, maybe you can use our 2.4.3 beta version.  downloadLink: cocos-dashboard://download/2d_2.4.3-beta.3
