### ISSUE TITLE
job-cache-manager将绝对路径写入cacheList有bug，iOS沙盒路径会变

### ISSUE THREAD

**Issue by neufeng** [cocos-creator-packages/jsb-adapter#334]
iOS下app每次启动沙盒Documents目录路径是会变的，现在代码里将资源的绝对路径写入缓存cacheList.json文件，是有问题的，下次再启动app会因为路径变了，加载图片失败。应该只存相对路径，沙盒路径实时获取再拼接绝对路径。
是没人用网络图片么，这么严重的bug，没发现？！！！！
<img width="1020" alt="屏幕快照 2020-08-27 下午12 36 46" src="https://user-images.githubusercontent.com/3053458/91385334-3c579300-e863-11ea-9532-9a8683737dda.png">

**Comment by holycanvas** [comment]
2.4.3已修复，感谢反馈
