### ISSUE TITLE
Memory leak: Skeleton JSB did not call back setDestroyCallback.

### ISSUE THREAD

**Issue by smallmain** [cocos-creator-packages/jsb-adapter#370]
https://github.com/cocos-creator-packages/jsb-adapter/blob/2459b84dca88b4cb64e21e7080dc02506acad6f4/engine/jsb-spine-skeleton.js#L57

https://github.com/cocos-creator-packages/jsb-adapter/blob/2459b84dca88b4cb64e21e7080dc02506acad6f4/engine/jsb-spine-skeleton.js#L52

![image](https://user-images.githubusercontent.com/28684663/217202879-4c6fed51-1979-42c6-b330-ba20d60f69a4.png)

This callback will never execute, resulting in an invalid texture object in the _textureKeyMap.

**Comment by dumganhar** [comment]
Which Creator version are you using?

**Comment by smallmain** [comment]
2.4.10

**Comment by dumganhar** [comment]
Did skeletonDataMgr be garbage-collected? If it didn't, the associated JS callback will not be collected too.
And when did you insert Texture2d to the weakmap?

**Comment by smallmain** [comment]
I'm not sure, the above is the engine code, not my user code, I'm a feature that reads _textureMap and finds that even if the texture2D inside is released, it still exists in this WeakMap.

Steps to trigger it.

1. Load a skeleton, play it
2. destroy the node and release the resources (including the referenced texture2d)
3. Load the same skeleton again and check _textureMap to find two texture2d, which are not freed

**Comment by zhakesi** [comment]
@smallmain please try this pr. Thanks for your feedback.
* https://github.com/cocos/engine-native/pull/4307

**Comment by Sunny-guangge** [comment]
@smallmain how to solve this question？

**Comment by smallmain** [comment]
> @smallmain how to solve this question？

You could try merging this pr, I haven't tested if it works.

**Comment by Sunny-guangge** [comment]
> > @smallmain how to solve this question？
> 
> You could try merging this pr, I haven't tested if it works.

I tried it, it doesn't work

**Comment by Sunny-guangge** [comment]
> > @smallmain how to solve this question？
> 
> You could try merging this pr, I haven't tested if it works.

and now it crashed at ios17beta

**Comment by dumganhar** [comment]
Oops, did it only crash on iOS 17 beta?

**Comment by Sunny-guangge** [comment]
![image](https://github.com/cocos-creator-packages/jsb-adapter/assets/11921153/f9402714-472f-43be-873f-6ed1e31302bc)
js_cocos2dx_spine_SkeletonDataMgr_setDestroyCallback   call js function crash on iOS 17 beta

**Comment by dumganhar** [comment]
Create an issue here https://github.com/cocos/cocos-engine/issues/16033

**Comment by zxx43** [comment]
> ![image](https://user-images.githubusercontent.com/11921153/261549152-f9402714-472f-43be-873f-6ed1e31302bc.png) js_cocos2dx_spine_SkeletonDataMgr_setDestroyCallback call js function crash on iOS 17 beta

Do you have project to show?

**Comment by zxx43** [comment]
> ![image](https://user-images.githubusercontent.com/11921153/261549152-f9402714-472f-43be-873f-6ed1e31302bc.png) js_cocos2dx_spine_SkeletonDataMgr_setDestroyCallback call js function crash on iOS 17 beta

try this pr: https://github.com/cocos/engine-native/pull/4321

**Comment by bofeng-song** [comment]
@Sunny-guangge After verifying with the official test cases, I can reproduce the issue you mentioned. However, the root cause is not memory leakage but rather delayed garbage collection in JavaScript. You can force the garbage collection by calling `jsb.garbageCollect();` in JavaScript. You can try triggering it at the end of the `onDestroy` method of the component or in the `onStart` method of the scene to see if it helps.
